---
- name: Install Icecast
  package: 
    name: icecast
    state: present

- name: Install Icecast configuration file
  template: 
    src: icecast.xml.j2 
    dest: "{{ icecast_config_file }}"
    owner: "{{ icecast_user }}" 
    group: "{{ icecast_group }}"  
    mode: 0640
  notify: 
    - reload icecast

- name: Enable Icecast service
  service:
    name: icecast
    enabled: yes
